version: "3"
services:
  service1:
    build:
      context: ./service1
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development

  service2:
    build:
      context: ./service2
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
